language: python
services:
    - redis-server
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install -U --editable ".[dev]"
script:
    - flake8 nameko_redis.py test
    - pytest -v
